#CI for product catalog service

name: product-catalog
on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v4
        
        - name: Setup Go 1.22
          uses: actions/setup-go@v4
          with:
            go-version: 1.22

        - name: build
          run: |
            cd catalog
            go mod download
            go build -o product-catalog-service ./main.go

        - name: run tests
          run: |
            cd catalog 
            go test ./...
        
    code-quality:
        runs-on: ubuntu-latest

        steps:
        - name: checkout code
          uses: actions/checkout@v4
        
        - name: Setup Go 1.22
          uses: actions/setup-go@v2
          with:
           go-version: 1.22
        
        - name: Run golangci-lint
          uses: golangci/golangci-lint-action@v6
          with:
            version: v1.55.2
            # run: golangci-lint run
            working-directory: catalog

    docker:
        runs-on: ubuntu-latest
        
        needs: build

        steps:
        - name: checkout code
          uses: actions/checkout@v4
        
        - name: Install Docker image
          uses: docker/setup-buildx-action@v1

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
        
        - name: Build and push Docker image
          uses: docker/build-push-action@v6
          with:
            context: catalog
            file: catalog/Dockerfile
            push: true
            tags: kdprasad028/product-catalog:${{github.run_id}}

    update-k8s:
        runs-on: ubuntu-latest

        needs: docker

        steps:
        - name: checkout code
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Update tag with kubernetes manifest
          run: |
            sed -i "s|image: .*|image: ${{secrets.DOCKER_USERNAME}}/product-catalog:${{github.run_id}}|" ./k8s-yamls/productcatalog/deploy.yaml
        
        - name: Commit and push changes
          run: |
            git config --global user.name "aikdp"
            git config --global user.email "kdprasad028@gmail.com"
            git add ./k8s-yamls/productcatalog/deploy.yaml
            git commit -m "Update image tag to ${{github.run_id}}"
            git push origin HEAD:main -f
